name: california
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - geopandas=1.0.1
  - pandas=2.2.3
  - numpy=2.2.5
  - shapely=2.0.6
  - joblib=1.4.2
  - scikit-learn=1.6.1
  - pydeck=0.9.1
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - folium=0.19.5
  - lightgbm=4.6.0
  - xgboost=2.1.4
  - pip=25.0
  - pip:
      - streamlit==1.45.1
      - altair==5.5.0
      - mlflow==2.22.0
      - fastapi==0.115.12
      - uvicorn==0.34.3