name: california
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - geopandas
  - pandas
  - numpy
  - shapely
  - joblib
  - scikit-learn
  - pydeck
  - pip
  - pip:
      - streamlit